version: "3.8"

services:
  mongoservice:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongovol:/data/db

    # restart: always
  api:
    build: ./
    ports:
      - "3000:3000"
    depends_on:
      - mongoservice
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    # restart: always

volumes:
  mongovol:
